In [1]:
import tensorflow as tf
import numpy as np
from PIL import Image
import os

def parse_png_to_tensor(image_path: str) -> tf.Tensor:
    """
    Parses a PNG image file into a TensorFlow tensor.

    This function is updated to be compatible with a TensorFlow training loop.
    It converts the image to RGB format, normalizes the pixel values to a
    0-1 range, and adds a batch dimension.

    Args:
        image_path (str): The file path to the PNG image.

    Returns:
        tf.Tensor: A TensorFlow tensor of the image with a shape of
                   (1, height, width, 3). Returns an empty tensor if the file
                   cannot be processed.
    """
    if not os.path.exists(image_path):
        print(f"Error: File not found at {image_path}")
        return tf.empty(0)

    try:
        # Open the image file
        image = Image.open(image_path)
        
        # Convert the image to RGB format. This handles different modes like RGBA or P.
        image = image.convert('RGB')
        
        # Convert the PIL Image object to a NumPy array.
        # The shape of the array will be (height, width, channels)
        numpy_array = np.array(image, dtype=np.float32)
        
        # Normalize the pixel values from 0-255 to 0.0-1.0
        normalized_array = numpy_array / 255.0
        
        # Convert the NumPy array to a TensorFlow tensor.
        # The tensor will have a shape of (height, width, channels)
        image_tensor = tf.convert_to_tensor(normalized_array)
        
        # Add a batch dimension at the beginning to match the expected
        # input shape for a model (batch_size, height, width, channels)
        final_tensor = tf.expand_dims(image_tensor, axis=0)

        return final_tensor

    except Exception as e:
        print(f"An error occurred while processing the image: {e}")
        return tf.empty(0)

# --- Example Usage ---
if __name__ == "__main__":
    # Create a dummy PNG file for testing
    dummy_image_path = "test_image.png"
    
    # Create a 100x100 white image with RGB channels
    dummy_image = Image.new('RGB', (100, 100), 'white')
    dummy_image.save(dummy_image_path)
    print(f"Created a dummy image at: {dummy_image_path}")

    # Call the parse function on the dummy image
    image_tensor = parse_png_to_tensor(dummy_image_path)

    # Check the result
    if image_tensor.shape.num_elements() > 0:
        print("\nSuccessfully converted image to TensorFlow tensor!")
        print(f"Tensor shape: {image_tensor.shape}")
        print(f"Data type: {image_tensor.dtype}")
    else:
        print("\nFailed to convert image to tensor.")

    # Clean up the dummy file
    os.remove(dummy_image_path)
    print(f"\nCleaned up dummy file: {dummy_image_path}")


Created a dummy image at: test_image.png

Successfully converted image to TensorFlow tensor!
Tensor shape: (1, 100, 100, 3)
Data type: <dtype: 'float32'>

Cleaned up dummy file: test_image.png


2025-09-13 15:20:33.426879: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-09-13 15:20:33.426914: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-09-13 15:20:33.426927: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-09-13 15:20:33.427287: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-09-13 15:20:33.427668: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [ ]:

labels = os.listdir("./dataset")
labels.remove(".DS_Store")
print(labels)
y = tf.zeros(len(os.listdir("./dataset/000000/")), dtype=tf.int32)
for i in range(1, len(labels)):
    y = tf.concat([y, tf.ones(len(os.listdir("./dataset/" + labels[i])), dtype=tf.int32) * i], axis=0)


['500000', '000200', '000500', '002000', '200000', '100000', '001000', '050000', '005000', '020000', '010000', '000000']


<tf.Tensor: shape=(2712,), dtype=int32, numpy=array([ 0,  0,  0, ..., 11, 11, 11], dtype=int32)>

In [15]:
label0List = os.listdir("./dataset/000000/")
X = [parse_png_to_tensor("./dataset/000000/" + img) for img in label0List]
for i in range(1, len(labels)):
    labelList = os.listdir("./dataset/" + labels[i] + "/")
    labelTensor = [parse_png_to_tensor("./dataset/" + labels[i] + "/" + img) for img in labelList]
    X = tf.concat([X, labelTensor], axis = 0)

X = tf.squeeze(X, axis=1)
X.shape

TensorShape([2712, 144, 192, 3])

In [ ]:
# Merge all the code into a single script

import tensorflow as tf
import numpy as np
from PIL import Image
import os

def parse_png_to_tensor(image_path: str) -> tf.Tensor:
    """
    Parses a PNG image file into a TensorFlow tensor.

    This function is updated to be compatible with a TensorFlow training loop.
    It converts the image to RGB format, normalizes the pixel values to a
    0-1 range, and adds a batch dimension.

    Args:
        image_path (str): The file path to the PNG image.

    Returns:
        tf.Tensor: A TensorFlow tensor of the image with a shape of
                   (1, height, width, 3). Returns an empty tensor if the file
                   cannot be processed.
    """
    if not os.path.exists(image_path):
        print(f"Error: File not found at {image_path}")
        return tf.empty(0)

    try:
        # Open the image file
        image = Image.open(image_path)
        
        # Convert the image to RGB format. This handles different modes like RGBA or P.
        image = image.convert('RGB')
        
        # Convert the PIL Image object to a NumPy array.
        # The shape of the array will be (height, width, channels)
        numpy_array = np.array(image, dtype=np.float32)
        
        # Normalize the pixel values from 0-255 to 0.0-1.0
        normalized_array = numpy_array / 255.0
        
        # Convert the NumPy array to a TensorFlow tensor.
        # The tensor will have a shape of (height, width, channels)
        image_tensor = tf.convert_to_tensor(normalized_array)
        
        # Add a batch dimension at the beginning to match the expected
        # input shape for a model (batch_size, height, width, channels)
        final_tensor = tf.expand_dims(image_tensor, axis=0)

        return final_tensor

    except Exception as e:
        print(f"An error occurred while processing the image: {e}")
        return tf.empty(0)

# --- Example Usage ---
if __name__ == "__main__":
    # Create a dummy PNG file for testing
    dummy_image_path = "test_image.png"
    
    # Create a 100x100 white image with RGB channels
    dummy_image = Image.new('RGB', (100, 100), 'white')
    dummy_image.save(dummy_image_path)
    print(f"Created a dummy image at: {dummy_image_path}")

    # Call the parse function on the dummy image
    image_tensor = parse_png_to_tensor(dummy_image_path)

    # Check the result
    if image_tensor.shape.num_elements() > 0:
        print("\nSuccessfully converted image to TensorFlow tensor!")
        print(f"Tensor shape: {image_tensor.shape}")
        print(f"Data type: {image_tensor.dtype}")
    else:
        print("\nFailed to convert image to tensor.")

    # Clean up the dummy file
    os.remove(dummy_image_path)
    print(f"\nCleaned up dummy file: {dummy_image_path}")


labels = os.listdir("./dataset")
labels.remove(".DS_Store")
print(labels)
y = tf.zeros(len(os.listdir("./dataset/000000/")), dtype=tf.int32)
for i in range(1, len(labels)):
    y = tf.concat([y, tf.ones(len(os.listdir("./dataset/" + labels[i])), dtype=tf.int32) * i], axis=0)

label0List = os.listdir("./dataset/000000/")
X = [parse_png_to_tensor("./dataset/000000/" + img) for img in label0List]
for i in range(1, len(labels)):
    labelList = os.listdir("./dataset/" + labels[i] + "/")
    labelTensor = [parse_png_to_tensor("./dataset/" + labels[i] + "/" + img) for img in labelList]
    X = tf.concat([X, labelTensor], axis = 0)

X = tf.squeeze(X, axis=1)
X, y


Created a dummy image at: test_image.png

Successfully converted image to TensorFlow tensor!
Tensor shape: (1, 100, 100, 3)
Data type: <dtype: 'float32'>

Cleaned up dummy file: test_image.png
['500000', '000200', '000500', '002000', '200000', '100000', '001000', '050000', '005000', '020000', '010000', '000000']


(<tf.Tensor: shape=(2712, 1, 144, 192, 3), dtype=float32, numpy=
 array([[[[[0.32941177, 0.34509805, 0.3254902 ],
           [0.29411766, 0.34901962, 0.30980393],
           [0.28627452, 0.36078432, 0.28235295],
           ...,
           [0.18431373, 0.15686275, 0.15686275],
           [0.21568628, 0.16470589, 0.10980392],
           [0.1882353 , 0.20392157, 0.14509805]],
 
          [[0.29411766, 0.3254902 , 0.32156864],
           [0.2901961 , 0.34117648, 0.32156864],
           [0.2784314 , 0.3372549 , 0.32156864],
           ...,
           [0.20784314, 0.20392157, 0.2       ],
           [0.2       , 0.16862746, 0.16470589],
           [0.23137255, 0.2       , 0.21568628]],
 
          [[0.28627452, 0.32156864, 0.3137255 ],
           [0.2901961 , 0.33333334, 0.31764707],
           [0.28627452, 0.33333334, 0.32941177],
           ...,
           [0.1882353 , 0.18039216, 0.16470589],
           [0.21960784, 0.18431373, 0.19215687],
           [0.23529412, 0.1882353 , 0.19215687]]

In [12]:
len(X), len(y)

(2712, 2712)